stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - echo "Building the application..."
    - echo "Build complete."

test-job:
  stage: test
  script:
    - echo "Testing"
