image: python:3.12

stages:
  - cleanup
  - setting_up
  - analyse_code
  - generate_pr
  - run_api


setup:
  stage: setting_up
  tags:
    - docker
  script:
    - python --version
    - pip --version
    - python -m venv venv  # Create a virtual environment
    - source venv/bin/activate # So requirements can be used across diff jobs
    - pip install --upgrade pip ruff flake8  # Install requirements
  cache:
    key: requirements    #cache/store dependencies
    paths:
      - venv/
  artifacts:
    paths:
      - venv/
    expire_in: 1 week



analyse:
  stage: analyse_code
  tags:
    - docker
  script:
    - source venv/bin/activate
    - export PYTHONPATH=$(pwd)
    - echo "Running custom Python script"
    - pip install litellm
    - python backend/app/scripts/run_scripts.py --filePath backend/app/scripts/fileForTesting.py > report.md 2>&1 || true
  artifacts:
    paths:
      - report.md
    expire_in: 1 week


generate_pr:
  stage: generate_pr
  tags:
    - docker
  script:
    - source venv/bin/activate
    - echo "Generating PR Title and Description"
    - echo "### PR Title" > pr_description.md
    - echo "" >> pr_description.md
    - echo "#### Key Findings:" >> pr_description.md
    - cat report.md | tail -n 10 >> pr_description.md  # Include the last 10 lines of the report
    - echo "" >> pr_description.md
    - echo "#### Recent Code Changes:" >> pr_description.md
    - git diff --name-status HEAD~1 >> pr_description.md  # Add modified files
    - echo "" >> pr_description.md
    - echo "#### Commit Logs:" >> pr_description.md
    - git log -3 --pretty=format:"- %h %s" >> pr_description.md  # Last 3 commits
  artifacts:
    paths:
      - pr_description.md
    expire_in: 1 week