stages:
  - setup
  - run_scripts

install_python:
  stage: setup
  script:
    - echo "Installing Python and pip"
    - sudo apt-get update && sudo apt-get install -y python3 python3-pip
    - python3 --version
    - pip --version