image: python:3.12

stages:
  - cleanup
  - setting_up
  - analyse_code
  - run_api


setup:
  stage: setting_up
  tags:
    - docker
  script:
    - python --version
    - pip --version
    - python -m venv venv  # Create a virtual environment
    - source venv/bin/activate # So requirements can be used across diff jobs
    - pip install --upgrade pip ruff flake8  # Install requirements
  cache:
    key: requirements    #cache/store dependencies
    paths:
      - venv/
  artifacts:
    paths:
      - venv/
    expire_in: 1 week



analyse:
  stage: analyse_code
  tags:
    - docker
  script:
    - source venv/bin/activate
    - export PYTHONPATH=$(pwd)
    - echo "Running custom Python script"
    - pip install litellm
    - python backend/app/scripts/run_scripts.py --filePath backend/app/scripts/fileForTesting.py > report.md 2>&1 || true
  artifacts:
    paths:
      - report.md
    expire_in: 1 week