stages:
  - cleanup
  - build
  - test

cleanup-job:
  stage: cleanup
  script:
    - echo "Cleaning up workspace..."
    - rm -rf temp_files/ || true  
    - echo "Cleanup complete."

build-job:
  stage: build
  script:
    - echo "Building"

test-job:
  stage: test
  script:
    - echo "Testing"
