image: python:3.12

stages:
  - setting_up
  - analyse_code
  - commit_fixes

variables:
  GIT_HTTP_PROXY: ""
  GIT_HTTPS_PROXY: ""
  NO_PROXY: "gitlab.com,*.gitlab.net"
  JIRA_URL: "https://tcd-team-ayl4vbq6.atlassian.net"
  JIRA_EMAIL: "eortiz@tcd.ie"
  BRANCH_NAME: "AUT-2"
  GITLAB_API_URL: "https://gitlab.com"
  # Ensure these tokens are set in your CI/CD variables.
  OPENAI_API_KEY: "$OPENAI_API_KEY"
  GITLAB_API_TOKEN: "$GITLAB_API_TOKEN"
  # Disable shallow cloning so the complete commit history is available.
  GIT_DEPTH: "0"

setup:
  stage: setting_up
  script:
    - python --version
    - pip --version
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip ruff flake8 requests python-dotenv litellm tiktoken
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - venv/
  artifacts:
    paths:
      - venv/
    expire_in: 1 week

analyse:
  stage: analyse_code
  script:
    - apt-get update && apt-get install -y netcat-openbsd dnsutils
    - source venv/bin/activate
    # Ensure the full history is available (this is extra safety; GIT_DEPTH: 0 usually does it).
    - git fetch --unshallow || true
    - export PYTHONPATH=$(pwd)
    - echo "Running analysis on changed Python files..."
    - pip install -r backend/requirements.txt
    # Use CI_PROJECT_URL so the script auto-detects the repository URL.
    - python backend/app/scripts/analyze_codebase_script.py --repoURL "$CI_PROJECT_URL" --jiraTicket "$BRANCH_NAME"
    - cat overall_report_id.txt  # Debug: show the overall report ID
  artifacts:
    paths:
      - report.md
      - overall_report_id.txt
    expire_in: 1 week

commit_fixes:
  stage: commit_fixes
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^fixes-/'
      when: never
    - when: on_success
  script:
    - apt-get update && apt-get install -y git
    - source venv/bin/activate
    - pip install -r backend/requirements.txt
    # Configure Git author identity for the commit.
    - git config --global user.email "ci@example.com"
    - git config --global user.name "GitLab CI"
    - export LATEST_OVERALL_REPORT_ID=$(cat overall_report_id.txt)
    - python backend/app/scripts/analyze_codebase_script.py --fix
  artifacts:
    paths:
      - report.md
    expire_in: 1 week
