image: python:3.12

stages:
  - upload_and_archive

commit_and_upload:
  stage: upload_and_archive
  script:
    # 1. Print commit message
    - echo "Commit Message:" ${CI_COMMIT_MESSAGE}

    # 2. Install dependencies with caching
    - echo "Installing dependencies"
    - pip install --cache-dir .cache/pip -r backend/requirements.txt

  cache:
    paths:
      - .cache/pip  # Cache pip packages for faster builds
