image: python:3.12

stages:
  - cleanup
  - setting_up
  - analyse_code
  - generate_pr
  - run_api

setup:
  stage: setting_up
  tags:
    - docker
  script:
    - python --version
    - pip --version
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip ruff flake8
  cache:
    key: requirements
    paths:
      - venv/
  artifacts:
    paths:
      - venv/
    expire_in: 1 week

run_api:
  stage: run_api
  tags:
    - docker
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r backend/requirements.txt
    - echo "Starting API with uvicorn"
    - uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --log-level debug &
    - sleep 5  # Give API time to start
    - ps aux | grep uvicorn  # Check if Uvicorn is running
    - echo "Waiting for API to be ready..."
    - for i in {1..10}; do curl -s http://localhost:8000/health && break || sleep 5; done
    - echo "Sending request to the API"
    - curl -X GET http://localhost:8000/analyze -o response.json
    - cat response.json

  artifacts:
    paths:
      - response.json
    expire_in: 1 week
