image: python:3.12

stages:
  - run_scripts
  - test_scripts

run_python_scripts:
  stage: run_scripts
  tags:
    - docker
  script:
    - echo "Python version check"
    - python --version
    - pip --version
    - pip install -r backend/requirements.txt

test_python_scripts:
  stage: test_scripts
  tags:
    - docker
  script:
    - python -c "print('Hello World')"
