stages:
  - cleanup
  - build
  - test

cleanup-job:
  stage: cleanup
  script:
    - echo "Running cleanup" 
    - docker system prune -af 
    - rm -rf /tmp/* 

build-job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - echo "Building the application..."
    - echo "Build complete."
  artifacts:
    paths:
      - build/
    expire_in: 1hr

test-job:
  stage: test
  script:
    - echo "Testing"
