stages:
  - analyze
  - upload

print-commit-message:
  stage: analyze
  script:
    - echo "Commit Message:" ${CI_COMMIT_MESSAGE}

send-file-to-api:
  stage: upload
  script:
    - echo "sending RAW FILE to api endpoint"
   # - curl -X POST "https://api_endpoint" -H "Content-Type: application/octet-stream" --data-binary @example.py
