stages:
  - analyze_and_upload

commit_and_upload:
  stage: analyze_and_upload
  script:
    - echo "Commit Message:" ${CI_COMMIT_MESSAGE}
    - echo "Sending RAW FILE to API endpoint"
    # Uncomment the next line to actually send the raw file, need to add in api address
    # Can be changed to send as json if needed
    # - curl -X POST "https://api_endpoint" -H "Content-Type: application/octet-stream" --data-binary @example.py
