image: python:3.12


stages:
  - setting_up
  - run_api

setup:
  stage: setting_up
  tags:
    - docker
  script:
    - python --version
    - pip --version
    - pip cache purge  # Clear pip's cache
    - rm -rf /tmp/*  # Remove temporary files
    - rm -rf /var/tmp/*  # Clean up additional temporary directories
    - python -m venv venv  # Create a virtual environment 
    - source venv/bin/activate # So requirements can be used across diff jobs
    - pip install --upgrade pip ruff flake8  # Install requirements
  cache:
    key: requirements    #cache/store dependencies
    paths:
      - venv/
  artifacts:
    paths:
      - venv/
    expire_in: 1 week


run_api:
  stage: run_api
  tags:
    - docker
  script:
    - source venv/bin/activate
    - pip install fastapi uvicorn requests
    - echo "Starting API with uvicorn"
    - nohup uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 &
    - sleep 5
    - echo "Sending request to the API"
    - curl -X GET http://127.0.0.1:8000/analyze -o response.json  # Send a request to the running API
    - cat response.json

  artifacts:
    paths:
      - response.json
    expire_in: 1 week


